chronosphereio/terraform-provider-chronosphere

.github/workflows/ci.yml
Use the dangoslen/changelog-enforcer marketplace action to ensure that the CHANGELOG.md
is being updated with each PR merged into the repo. This can be bypassed for
changes that are not customer impacting by applying the `skip-changelog` or
`ignore-release` labels to the PR.
=> add CI job to enforce CHANGELOG.md updates

CHANGELOG.md, chronosphere/intschema/drop_rule.go, chronosphere/resource_drop_rule.go, chronosphere/tfschema/drop_rule.go
drop_nan_value allows you to drops datapoints if the datapoint
values are NaN. This change adds support for that field.
=> Add support for `drop_nan_value` in Drop Rule resource

CHANGELOG.md, chronosphere/resource_rollup_rule.go, chronosphere/tfschema/rollup_rule.go
Remove local rollup rule validation
Instead of doing validation locally we will start to fully rely on
dry run validation that we do for all resources that support it.
The rationale behind this is that changes/additions to the APIs
may render a local check obsolete and require a new version of
the Terraform provider when it is not necessary. This has been
seen recently as the result of additionally functionality added
to rollup rules
update CHANGELOG
=> Remove local rollup rule validation

.github/workflows/ci.yml, CHANGELOG.md, chronosphere/provider_test.go, chronosphere/tfschema/gcp_metrics_integration.go
Follow-up to #11, which added name with Optional=false, but this fails terraform's schema validation:
```
provider local/chronosphereio/chronosphere has invalid schema for
managed resource type "chronosphere_gcp_metrics_integration_unstable",
which is a bug in the provider: "1 error occurred:\n\t* name: must set
Optional, Required or Computed\n\n"..
```
Add a test that gets to the step where TF loads the schema without requiring remote calls, verifying that the test fails without the fix.
=> Add provider schema sanity test, fix GCP schema

CHANGELOG.md, chronosphere/intschema/dashboard.go, chronosphere/resource_dashboard.go, chronosphere/tfschema/dashboard.go
Originally the name was extracted from the dashboard_json metadata. This is confusing/inconsistent with how we treat other resources. The public API also supports a top level name field. We have deprecated the metadata field as well.
This PR adds the name field to our dashboard resource, implementing a one_of between name and json.metadata.name.
The lack of either name fields being set results in a validation error from the API.
=> Adds name field to chronosphere_dashboard

CHANGELOG.md, chronosphere/resource_rollup_rule.go, chronosphere/tfschema/rollup_rule.go
[sc-81013]
Currently, migrating from storage_policies to interval is not possible as the provider receives both fields set, even if storage_policies is no longer set. This seems like an issue with the plugin sdk, as it's passing the last returned server value, even if the user deletes the config.
However, we can workaround this by:
* Ensuring the config doesn't allow both to be set by using `ConflictsWith`, which only triggers if the config has both set.
* Clearing storage_policies if it's set alongside interval, since we know that both cannot be set due to the above validation.
=> Support migration from storage_policies to interval [sc-81013]

CHANGELOG.md, chronosphere/tfschema/mapping_rule.go, chronosphere/tfschema/rollup_rule.go
interval replaces storage_policies, is simpler for users, and avoids users needing to figure out the correct retention value.
=> Deprecate storage policies in mapping and rollup rules

CHANGELOG.md, chronosphere/tfschema/mapping_rule.go
=> Deprecate mapping_rule.drop_timestamp

chronosphere/intschema/bucket.go, chronosphere/intschema/generateintschema/main.go, chronosphere/intschema/notification_policy.go, chronosphere/resource_bucket.go, chronosphere/resource_notification_policy_independent.go
This doesn't impact the provider logic, this makes it easier for tests to generate tf schemas where the notification_policy_data is a reference.
=> intschema: Use tfid for bucket.notification_policy_data

CHANGELOG.md, chronosphere/generated_resources.gen.go, chronosphere/generateresources/main.go, chronosphere/generic_resource.go, chronosphere/pagination/generatepagination/main.go, chronosphere/registry/registry.go, chronosphere/resource_otel_metrics_ingestion.go, chronosphere/resource_resource_pools_config.go, chronosphere/resource_trace_tail_sampling_rules.go
Currently, resource pools rely on client-side validation, which requires manually
keeping it in-sync with server-side validation (as in #50).
Instead, we can replace the client-side validation with server-side dry-run validation.
Instead of manually calling dry-run validation, use genericResource and generate
singleton CRUD wrappers.
Resource pools have some custom mapping from the server-side schema to the
terraform schema based on what fields are locally set (e.g., `pool` vs `pools`)
which is supported by new support in the converter to `normalize`.
=> resource_pools: Use genericResource, and use server dry-run to replace validation

chronosphere/generic_resource.go, chronosphere/resource_blackhole_alert_notifier.go, chronosphere/resource_bucket.go, chronosphere/resource_classic_dashboard.go, chronosphere/resource_collection.go, chronosphere/resource_dashboard.go, chronosphere/resource_dataset.go, chronosphere/resource_derived_label.go, chronosphere/resource_derived_metric.go, chronosphere/resource_drop_rule.go, chronosphere/resource_email_alert_notifier.go, chronosphere/resource_gcp_metrics_integration.go, chronosphere/resource_mapping_rule.go, chronosphere/resource_monitor.go, chronosphere/resource_notification_policy_independent.go, chronosphere/resource_opsgenie_alert_notifier.go, chronosphere/resource_pagerduty_alert_notifier.go, chronosphere/resource_recording_rule.go, chronosphere/resource_rollup_rule.go, chronosphere/resource_slack_alert_notifier.go, chronosphere/resource_team.go, chronosphere/resource_trace_jaeger_remote_sampling_strategy.go, chronosphere/resource_trace_metrics_rule.go, chronosphere/resource_victorops_alert_notifier.go, chronosphere/resource_webhook_alert_notifier.go
Newer versions of Go are able to infer the type parameters, so we can simplify and drop these.
This also drops newNoConvertResource which is unused.
=> Drop unused type params + methods in genericResource

chronosphere/generated_resources.gen.go, chronosphere/registry/registry.go, chronosphere/resource_otel_metrics_ingestion.go
Simplify the Otel resource by relying on genericResource support for singletons added in #51.
This replaces the custom validation with `ValidateDryRun` which similarly tries to convert the scheam to an API model, but also triggers a dry-run update call to validate the entity.
=> Use genericResource for OtelMetricsIngestion

chronosphere/generated_resources.gen.go, chronosphere/registry/registry.go, chronosphere/resource_trace_tail_sampling_rules.go
Simplify the Otel resource by relying on genericResource support for singletons added in #51.
This replaces the custom validation with ValidateDryRun which similarly tries to convert the scheam to an API model, but also triggers a dry-run update call to validate the entity.
=> Use genericResource for TraceTailSamplingRules

chronosphere/generateresources/main.go, chronosphere/registry/registry.go
DryRun is enabled for almost all resources, and it's easy to forget to enable for new resources, so flip the default so it's enabled by default and requires opting out.
The only resource without DryRun is TraceMetricsRule -- it's likely this was missed due to the opt-in nature, but it's not enabled in this PR to keep this change a pure refactor with no behavioural changes.
=> registry: Enable DryRun by default, make it opt-out

CHANGELOG.md, chronosphere/generated_resources.gen.go, chronosphere/registry/registry.go
Caught in #59 that TraceMetricsRule doesn't have dry-run enabled which was likely missed as it was opt-in previously.
=> trace_metrics_rule: Enable dry-run validation

CHANGELOG.md, chronosphere/provider.go
[sc-98152]
Dry-run also performs a create/update on the server, so should be
subject to the same concurrency limit. Limit concurrency of
CustomizeDiff which is where dry-run validation is implemented.
=> Limit dry-run concurrency similar to create/update/delete

Makefile, scripts/go-build-ldflags.sh
In the refactoring that was done for open-sourcing the Terraform
provider, the GIT_VERSION environment variable was moved out of
Makefile and into release scripts. This caused a few make
targets to output the wrong thing, but also caused releases
to fail release branch validation. This required that releases
using `SKIP_RELEASE_BRANCH_VALIDATION=true` which leave potential
for human error when making a release.
This PR moves GIT_VERSION back into Makefile and propagates it
along through the release scripts
=> fix release version check

chronosphere/intschema/generateintschema/main.go, chronosphere/intschema/log_allocation_config.go, chronosphere/resource_log_allocation_config.go, chronosphere/tfschema/log_allocation_config.go, examples/log-allocation-config/main.tf
The TF ecosystem uses `_id` fields for references to other objects. intschema also relies on the `_id` suffix to generate a field as a `tfid.ID`, allowing tests to use references.
We also need to handle dry-run validation when using a reference as the ID isn't known at plan time if it hasn't been created, so we replace it with a dummy value.
Note: This entity is still unstable, so this is not a breaking change.
=> log_allocation_config: Fix dataset reference

CHANGELOG.md, chronosphere/resource_slack_alert_notifier.go
[sc-111195]
Slack actions without `action_confirm_text` fail to create currently
as the TF model flattens confirmation fields into the action, and
always sends a non-nil confirmation field (though it may be empty).
Only set `ConfirmField` if it contains non-empty values.
=> slack: Don't require action_confirm_text in action [sc-111195]

CHANGELOG.md, chronosphere/intschema/mapping_rule.go, chronosphere/intschema/rollup_rule.go, chronosphere/resource_mapping_rule.go, chronosphere/resource_rollup_rule.go, chronosphere/tfschema/mapping_rule.go, chronosphere/tfschema/rollup_rule.go
[sc-111204]
When neither interval or storage_policy is specified, a server-side
default is returned. This causes a diff-after-apply, so mark the field
as computed.
Note: When using a computed field, if the user sets an explicitly value,
say `interval=60s`, and then removes that field, Terraform cannot
differentiate whether the value in the state is a server-side default or
previously set, and will continue to use the existing value as-is.
See https://github.com/hashicorp/terraform-plugin-sdk/issues/282
=> tfschema: Fix rollup/mapping rule interval diff after apply [sc-111204]

.goreleaser.yml, Makefile, scripts/increment_minor.sh, scripts/increment_patch.sh, scripts/next_version.sh, scripts/run_goreleaser.sh
This PR adds make targets for installing snapshots of the terraform provider for testing with a real version number instead of using the `0.0.1-dev` strategy we have been using up until now.
=> Add make targets to build and install snapshots for testing

CHANGELOG.md, chronosphere/resource_notification_policy.go
Allows creation of unowned notification policies and in-place updates to remove an owner from an existing policy.
Scenario test build 24 completed successfully.
=> Allow unowned notification policies

chronosphere/resource_notification_policy.go
Slug should not be allowed for inline policies. This invariant was inadvertently relaxed in #83 though never released.
Scenario test build 25 completed successfully.
=> Do not allow slug to be set for unnamed policies

chronosphere/resource_bucket.go, chronosphere/resource_notification_policy.go, chronosphere/resource_notification_policy_independent.go, chronosphere/tfschema/monitor.go, chronosphere/tfschema/notification_policy.go
=> Fix customized diff function and outdated references to policy ownership relationship to inline and independent policies

CHANGELOG.md, chronosphere/resource_resource_pools_config.go
When `default_pool` is unset, the conversion from tf schema to model
succeeds, and the config is applied, but when converting the server
model to intshema, it fails as a `nil` default pool is not handled.
=> resource-pools: Fix handling when default is unset [sc-116346]

CHANGELOG.md, chronosphere/resource_log_allocation_config.go, chronosphere/resource_notification_policy.go, chronosphere/resource_recording_rule.go, chronosphere/set_unknown.go, chronosphere/set_unknown_test.go
When a recording rule has `execution_group` and a `bucket_slug` set,
they're expected to match. However at dry-run time, the `bucket_slug`
may not be known yet and is set to a dummy value which won't match
`execution_group` and fail to validate.
Update validation to use the `execution_group` as the `bucket_slug`
if it's unknown.
As part of this, use a clearer value for unknown dry-run references.
=> Fix recording-rule dry-run when bucket/group are set [sc-125838]

README.md
We recently moved the Terraform documentation to a new TOOLS section of the docs. This PR updates the `README` to use the updated URLs.
=> [docs] Update README with current documentation URLs

CHANGELOG.md, chronosphere/intschema/slo.go, chronosphere/resource_slo.go, chronosphere/tfschema/slo.go, examples/slo/main.tf
These will supersede reporting_windows and the is preview flag
which will be deprecated in a future change.
Scenarios [PR](https://github.com/chronosphereio/terraform-provider-chronosphere-scenarios/pull/1089) [Run](https://buildkite.com/chronosphere/terraform-provider-tests/builds/7056#01961bf1-fff0-4433-a97d-696a460e0fc2)
=> Add time window and enable burn rate alerting fields to SLOs.

.goreleaser.yml, Makefile
When upgrading to goreleaser v2, there were some breaking
changes to the `make install-snapshot` target. The main
one is that goreleaser now includes arch versions (e.g. GOARM64 or GOAMD64)
in the build directory name: https://goreleaser.com/customization/builds/go/#why-is-there-a-_v1-suffix-on-amd64-builds
It doesn't seem there's a way to disable this, so
we have to work it into our Makefile.
=> Fix `make install-snapshot` for goreleaser v2.11.1

chronosphere/pagination/generatepagination/main.go, chronosphere/pagination/pagination.gen.go, chronosphere/resource_trace_tail_sampling_rules.go
Supporting code to implement generated import/export bindings
for singletons:
- `Singleton` bool on `registry.Resource`
- generated pagination bindings for singletons (return empty list if no singleton exists, else length=1 list). note, this is obviously a crappy interface, but it's helpful when generating code to have the same pagination signature as the other entities
- missing TraceTailSamplingRulesFromModel mapper
=> Supporting code for singleton export/import

CHANGELOG.md, chronosphere/enum/mode_type.go, chronosphere/intschema/drop_rule.go, chronosphere/resource_drop_rule.go, chronosphere/tfschema/drop_rule.go
Public API change: https://github.com/chronosphereio/monorepo/pull/71018, verified that the cloud deploy has gone out to production.
=> Update drop rules to support mode instead of active

CHANGELOG.md, chronosphere/enum/mode_type.go, chronosphere/intschema/drop_rule.go, chronosphere/resource_drop_rule.go, chronosphere/tfschema/drop_rule.go
This reverts commit da6ac31c192f36dba4c999f6ee94a39e717619e2.
Need to redo this because it's backwards incompatible given how server-side we always set `mode` field, whether the caller specified `active` OR `mode`.
See https://chronosphereio.slack.com/archives/C02J28DB9E3/p1759261803111469?thread_ts=1759245879.680839&cid=C02J28DB9E3
=> Revert "Update drop rules to support mode instead of active (#154)"
